# Generated by Django 4.1.2 on 2023-02-28 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0006_delete_users_alter_anime_rating'),
        ('users', '0002_useranime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranime',
            name='anime',
        ),
        migrations.AlterField(
            model_name='useranime',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anime_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranime',
            name='anime',
            field=models.ManyToManyField(blank=True, related_name='users', to='first_try.anime'),
        ),
    ]
