# Generated by Django 4.1.2 on 2023-03-04 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0006_delete_users_alter_anime_rating'),
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranime',
            name='anime',
        ),
        migrations.AlterField(
            model_name='useranime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranime',
            name='anime',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='first_try.anime'),
            preserve_default=False,
        ),
    ]
