# Generated by Django 4.1.2 on 2023-03-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0006_delete_users_alter_anime_rating'),
        ('users', '0005_remove_useranime_anime_alter_useranime_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_try.anime'),
        ),
    ]
