# Generated by Django 4.1.2 on 2023-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_favorite_genres_alter_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'USER', 'verbose_name_plural': 'USERS'},
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/vendor/users_images', verbose_name='IMAGE URL'),
        ),
    ]
