version: '3.9'

services:
  anitiming:
    build: .
    restart: always
    container_name: anitiming
    ports:
      - "8000:8000"
    volumes:
      - static:/var/www/static
    env_file:
      - .env
    depends_on:
     - db
  db:
    image: postgres:15
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - static:/var/www/static
    ports:
      - "80:80"
    depends_on:
      - anitiming




volumes:
  postgres_data:
  static:


    