version: '3.7'

services:
  web:
    build: .
    restart: always
    container_name: anitiming
    command: python manage.py runserver 127.0.0.1:8000
    env_file: .env
    ports:
     - "8000:8000"
    volumes:
      - /path/on/host:/path/in/container
    depends_on:
     - db
  db:
    image: postgres
    restart: always
    container_name: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:


    