# Generated by Django 4.1.2 on 2022-12-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
