# Generated by Django 4.1.2 on 2022-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('anime_list', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
