# Generated by Django 4.1.2 on 2022-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
