# Generated by Django 4.1.2 on 2023-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0004_alter_anime_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='image',
        ),
        migrations.AddField(
            model_name='anime',
            name='images',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='urls',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.TextField(null=True),
        ),
    ]
