# Generated by Django 4.1.2 on 2023-03-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0006_delete_users_alter_anime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
