# Generated by Django 4.1.2 on 2023-04-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0007_alter_anime_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-rating', 'name'], 'verbose_name': 'ANIME', 'verbose_name_plural': 'ANIMES'},
        ),
    ]
