# Generated by Django 4.2 on 2023-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0008_alter_anime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='images',
            field=models.ImageField(null=True, upload_to='static/vendor/anime_images'),
        ),
    ]
