# Generated by Django 4.2 on 2023-05-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_try', '0009_alter_anime_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
